### ISSUE TITLE
Add Privacy Policy

### ISSUE THREAD

**Issue by devarshishimpi** [devarshishimpi/Stone-CSS-Website#12]
Privacy policy link does not work.

**Comment by shashikantdev3** [comment]
Hey @devarshishimpi, Do you want a generic Privacy Policy or Do you have specific Privacy Policies.

Please let me know the details and assign it to me. Will add the Privacy Policy page.

**Comment by devarshishimpi** [comment]
Hi @shashikantdev3 ,

A generic Privacy Policy works as far as I can say with the User's privacy being prioritized, as well as keeping in mind that the project is open source.

Yes, I can assign it to You.

Thanks,
Devarshi Shimpi

**Comment by devarshishimpi** [comment]
Also, Do note that we just got a domain name for the project at : https://stonecss.com/
Planning to add to Google Search Index as well ( Currently doesn't come in Google Search Results, so direct website link )

**Comment by shashikantdev3** [comment]
Thanks for assigning me, I am on it.

**Comment by shashikantdev3** [comment]
> Hi @shashikantdev3 ,
> 
> A generic Privacy Policy works as far as I can say with the User's privacy being prioritized, as well as keeping in mind that the project is open source.
> 
> Yes, I can assign it to You.
> 
> Thanks, Devarshi Shimpi

@devarshishimpi, Okay so the Privacy Policy should follow CCPA and GDPR considerations?

If So then I have few questions related to the Privacy Policies (under Use of Information and Disclosure of Information), please answer below questions so that I can proceed further.
1. Users of this open source project will be all around the world (Including EU, UK, Switzerland, Iceland, Liechtenstein, or Norway, Canada and US) So, Do you want the privacy policy to be California Consumer Privacy Act (CCPA) compliant?
2. Can users create an account or register with the website (https://stonecss.com)?
3. Can users under the age of 18 can use the website/framework (Also Is this offered to users under the age of 13?)?
4. Are we intend to collect Personal Information/Sensitive Information directly from the user (It should not I guess but what's your say)?
5. Can users register for the website using Facebook, Google, or other social media accounts?
6. Will you be collecting any derivative data from your users?
7. Are you collecting personal information about your users from other sources?
8. Do you use personal information to provide your Services or fulfill contractual obligations with your users?
9. Are there any other important reasons you use your users' information?
10. Do you send marketing or promotional communications to your users?
11. Do you disclose or sell users' personal information to third parties?
12. Does your website accept payments online?
13. Can users upload or post content on your website?
This includes comments, articles, photos, audio, videos, user profile images, etc.
14. Does your website or app contain advertisements from third parties that are not affiliated with you?
15. Will you disclose any of your users' personal information to business affiliates?
Business affiliates include your parent company, subsidiaries, and joint venture partners.

16. How long will you keep the information that you've collected from your users?
i.   As long as the user has an account with us
ii.  A number of months after the user's account is terminated
iii. A number of months after the user's account becomes idle

17. Which of the following does your website or app use or plan to use?
i.   Cookies and/or web beacons
ii.  Google Maps APIs
iii. Both
iv. Neither

18. How can users contact you regarding CCPA-related questions?
i.   Email address
ii.  Toll-free phone number
iii. Contact form
iv, Other
20. What is the email address users should contact in case they have questions about your policy?
Please enter the email address of the person responsible for your privacy notice,
21. Can users update their consent preferences through their accounts?
22. Do you provide a service that allows users to send a request to view/edit/delete their personal information stored on your website and/or app?
This type of service could be an online request form, contact form, or a dedicated email address.
23. Do you provide a service that allows users to send a request to view/edit/delete their personal information stored on your website and/or app?
This type of service could be an online request form, contact form, or a dedicated email address.

24. What is the version date?

**Comment by devarshishimpi** [comment]
> > Hi @shashikantdev3 ,
> > A generic Privacy Policy works as far as I can say with the User's privacy being prioritized, as well as keeping in mind that the project is open source.
> > Yes, I can assign it to You.
> > Thanks, Devarshi Shimpi
> 
> @devarshishimpi, Okay so the Privacy Policy should follow CCPA and GDPR considerations?
> 
> If So then I have few questions related to the Privacy Policies (under Use of Information and Disclosure of Information), please answer below questions so that I can proceed further.
> 
> 1. Users of this open source project will be all around the world (Including EU, UK, Switzerland, Iceland, Liechtenstein, or Norway, Canada and US) So, Do you want the privacy policy to be California Consumer Privacy Act (CCPA) compliant?
> 2. Can users create an account or register with the website (https://stonecss.com)?
> 3. Can users under the age of 18 can use the website/framework (Also Is this offered to users under the age of 13?)?
> 4. Are we intend to collect Personal Information/Sensitive Information directly from the user (It should not I guess but what's your say)?
> 5. Can users register for the website using Facebook, Google, or other social media accounts?
> 6. Will you be collecting any derivative data from your users?
> 7. Are you collecting personal information about your users from other sources?
> 8. Do you use personal information to provide your Services or fulfill contractual obligations with your users?
> 9. Are there any other important reasons you use your users' information?
> 10. Do you send marketing or promotional communications to your users?
> 11. Do you disclose or sell users' personal information to third parties?
> 12. Does your website accept payments online?
> 13. Can users upload or post content on your website?
>     This includes comments, articles, photos, audio, videos, user profile images, etc.
> 14. Does your website or app contain advertisements from third parties that are not affiliated with you?
> 15. Will you disclose any of your users' personal information to business affiliates?
>     Business affiliates include your parent company, subsidiaries, and joint venture partners.
> 16. How long will you keep the information that you've collected from your users?
>     i.   As long as the user has an account with us
>     ii.  A number of months after the user's account is terminated
>     iii. A number of months after the user's account becomes idle
> 17. Which of the following does your website or app use or plan to use?
>     i.   Cookies and/or web beacons
>     ii.  Google Maps APIs
>     iii. Both
>     iv. Neither
> 18. How can users contact you regarding CCPA-related questions?
>     i.   Email address
>     ii.  Toll-free phone number
>     iii. Contact form
>     iv, Other
> 19. What is the email address users should contact in case they have questions about your policy?
>     Please enter the email address of the person responsible for your privacy notice,
> 20. Can users update their consent preferences through their accounts?
> 21. Do you provide a service that allows users to send a request to view/edit/delete their personal information stored on your website and/or app?
>     This type of service could be an online request form, contact form, or a dedicated email address.
> 22. Do you provide a service that allows users to send a request to view/edit/delete their personal information stored on your website and/or app?
>     This type of service could be an online request form, contact form, or a dedicated email address.
> 23. What is the version date?

@shashikantdev3 

Hi, Thanks For the updates.
Yes, it will follow CCPA and GDPR Policies.

As of your answers,
1. Yes, it should work with maximum privacy policies as brought by different countries.
2. No, not yet, but login and authentication is planned to be added ( approx in next 1-2 months )
3. Yes, users of any age can use this framework and all it's platforms.
4. No, we won't collect any sensitive or personal information from the user.
5. Yes, It is currently planned to be added, ( Github, Google, Gitlab are the ones to be added )
6. Yes, the users email address as of now is being collected for the purposes of the project and notified via email.
7. No, Personal Data collection will be only done through our services.
8. Personal information isn't collected, but if so, it will be only used for the project in the upcoming future.
9. No
10. Yes
11. Currently it is hosted on Netlify, so I see a chance of third-party data collection from Netlify. Once we move to our servers in the future, there will be no third-party dependencies.
12. No
13. Planned to add comments as a feature
14. As of now, No, but planned to add Google ads
15. Yes, it will be only shared with the Parent Company ( DVS Tech )
16.  As long as the user has an account with us. Rest data is deleted every one month.
17. No
18. Email : devarshishimpi@gmail.com Or The contact form to be added in the website ( Will be added in just 2-3 days )
19. devarshishimpi@gmail.com
20. Yes, they can
21. Yes, Online request form as well as the email method are open
22. Duplicate Question
23. Didn't get this question

If you need any more information/help/resources for the same, Do let me know with @

**Comment by shashikantdev3** [comment]
> 

@devarshishimpi, Thanks for the reply.

The last question (Q. 23) is about version date of the privacy policy that will be Effective Date for Privacy Policy, look below for the reference

![image](https://user-images.githubusercontent.com/52612360/182029476-848071e2-9969-4a0a-afca-a721fe4ca4e3.png)

**Comment by devarshishimpi** [comment]
@shashikantdev3 Oh yes, then I will update the answers according to the effective date. Most of them are still the same.

1. Yes, it should work with maximum privacy policies as brought by different countries.
2. No, not yet, but login and authentication is planned to be added ( approx in next 1-2 months )
3. Yes, users of any age can use this framework and all it's platforms.
4. No, we won't collect any sensitive or personal information from the user.
5. Yes, It is currently planned to be added, ( Github, Google, Gitlab are the ones to be added )
6. Yes, the users email address as of now is being collected for the purposes of the project and notified via email as well as the user's time of visit.
7. Yes, Google Analytics is used for the same, We are planning to only collect Personal Data through our services.
8. The data collected will only be used for the project purposes.
9. No
10. Yes
11. Currently it is hosted on Netlify, so I see a chance of third-party data collection from Netlify as well as Google Analytics for web traffic. Once we move to our servers in the future, there will be no third-party dependencies.
12. No
13. Planned to add comments as a feature
14. As of now, No, but planned to add Google ads
15. Yes, it will be only shared with the Parent Company ( DVS Tech )
16. As long as the user has an account with us. Rest data is deleted every one month.
17. Sessions will be added
18. Email : [devarshishimpi@gmail.com](mailto:devarshishimpi@gmail.com) Or The contact form on the website.
19. [devarshishimpi@gmail.com](mailto:devarshishimpi@gmail.com)
20. Yes, they can
21. Yes, Online request form as well as the email method are open
22. Duplicate Question
23. 15th August, 2022

**Comment by devarshishimpi** [comment]
@shashikantdev3 Any updates?

**Comment by shashikantdev3** [comment]
Hey @devarshishimpi, Please have a look on the document that I have shared with you on your mail id devarshishimpi@gmail.com and review the Data/Content of the privacy policy and let me know if anything is missing or needs to be changed.

**Comment by devarshishimpi** [comment]
> Hey @devarshishimpi, Please have a look on the document that I have shared with you on your mail id [devarshishimpi@gmail.com](mailto:devarshishimpi@gmail.com) and review the Data/Content of the privacy policy and let me know if anything is missing or needs to be changed.

@shashikantdev3 Have responded to the same.

**Comment by devarshishimpi** [comment]
@shashikantdev3 Is it ready by now? The broken links are affecting SEO heavily. Would love if it can be done a bit faster.

**Comment by shashikantdev3** [comment]
Hi @devarshishimpi. Yup it is ready. I'm going to make the PR in one hour.

**Comment by devarshishimpi** [comment]
@shashikantdev3 SEO has improved. The other link which is not working is of course the terms of use link. Once that's fixed, we'll have some good value in Search results.

Also, Regarding styling the privacy policy, I will do it, after which we can close the Issue

**Comment by shashikantdev3** [comment]
@devarshishimpi, sounds good. I'm working on the terms of use link.

**Comment by devarshishimpi** [comment]
> @devarshishimpi, sounds good. I'm working on the terms of use link.

@shashikantdev3 yes, saw the same.

**Comment by ArjunSharda** [comment]
I think this has to be closed as there is already a privacy policy.

**Comment by devarshishimpi** [comment]
> I think this has to be closed as there is already a privacy policy.

@ArjunSharda This will be closed after adding CSS to the privacy policy as currently it's just Plain HTML.
