### ISSUE TITLE
Fix footer emoji and add light and dark mode switch option.

### ISSUE THREAD

**Issue by Elu007** [devarshishimpi/Stone-CSS-Website#20]
Your website looks great but still, the footer emoji must be a red heart and if you are working with CSS then add a button to toggle between light and dark mode.

**Comment by devarshishimpi** [comment]
Hi @Elu007,

Thank You For Your Kind Words. Yes, work has already started with the footer emoji to be a red heart.
Regarding the light and dark more switch. Yes, I had the idea to implement it, but since this a landing page and will be replaced with the documentation later. I feel adding it to the final documentation and the final website which will replace this should be used with the Dark/Light Mode Toggle.

**Comment by Elu007** [comment]
Ok good to listen, if any where I can help please let me know, I will be delighted to help you.

**Comment by devarshishimpi** [comment]
> Ok good to listen, if any where I can help please let me know, I will be delighted to help you.

@Elu007 Sure, If you want to help with this as well, I can assign it to you. Keep it open until the red heart part Issue is being fixed.

**Comment by devarshishimpi** [comment]
@Elu007 Updates on the same. Just checked it, the issue remains with the desktop version as the mobile version loads it perfectly.

![image](https://user-images.githubusercontent.com/43378923/183030882-4809c847-a042-4055-abc9-52908ab19a70.png)

**Comment by devarshishimpi** [comment]
I see the website working fine and the second issue will be updated in the docs website on release.
